apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myappgaurav
  namespace: gaurav2
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
