apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gaurav-postgres-db
spec:
  serviceName: "gaurav-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: gaurav-postgres
  template:
    metadata:
      labels:
        app: gaurav-postgres
    spec:
      containers:
      - name: gaurav-postgres
        image: mangwani/k8sassignment:dbserverv10.0
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pvc-0f694a22-f378-47b4-ba5a-5e5975f609fb
          mountPath: /var/lib/postgresql/gaurav
        env:
        - name: POSTGRES_DB
          value: mydatabase
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
  volumeClaimTemplates: []
  volumes:
    - name: pvc-0f694a22-f378-47b4-ba5a-5e5975f609fb
      persistentVolumeClaim:
        claimName: gaurav-postgres-pvc
