apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80            # The port exposed by the service
      targetPort: 80       # The port on the container to which the service forwards traffic
  type: LoadBalancer      # Type LoadBalancer will expose the service externally
